import os, warnings
warnings.filterwarnings('ignore')
os.environ['CUDA_VISIBLE_DEVICES'] = '0' #################################

# imports
# import scipy.integrate as integrate
import scipy.io as io
# import numpy as np
import jax
import jax.numpy as jnp
import equinox as eqx
import diffrax 
from diffrax import diffeqsolve, ODETerm
from jax import random, jit
from tqdm import tqdm
from functools import partial
jax.config.update('jax_enable_x64', True)

# 2D GRF data generation
def GRF_2D_periodic(data_num, Nx, Ny, gamma, tau, sigma, key):
    # Eigenfunction from C = sigma^2(-Delta + tau^2 I)^(-gamma) on the unit square with periodic BC 
    # Eigenvalue: sigma^2 * (4pi^2 * (kx^2+ky^2) + tau^2)^(-gamma/2)
    keys = random.split(key,5)
    pi = jnp.pi
    freqx, freqy = Nx, Ny
    hfreqx, hfreqy = Nx//2+1, Ny//2+1
    
    ex,ey = jnp.meshgrid(jnp.arange(freqx),jnp.arange(freqy),indexing='xy')
    my_eigs = ((sigma**2)*(4*pi**2*(ex**2+ey**2)+tau**2)**(-gamma/2)).T
    
    coeff_normal = random.normal(keys[0],(data_num,freqx,hfreqy),dtype=jax.numpy.cdouble) + \
        1j*random.normal(keys[1],(data_num,freqx,hfreqy),dtype=jax.numpy.cdouble)
    coeff_decay = (Nx*Ny*my_eigs[:,:hfreqy]*coeff_normal) # IFFT scaling
    
    # real ifft2
    coeff_decay = coeff_decay.at[:,0,0].set(jnp.real(coeff_decay[:,0,0]))
    coeff_decay = coeff_decay.at[:,Nx//2,0].set(jnp.real(coeff_decay[:,Nx//2,0]))
    coeff_decay = coeff_decay.at[:,0,Ny//2].set(jnp.real(coeff_decay[:,0,Ny//2]))
    coeff_decay = coeff_decay.at[:,Nx//2,Ny//2].set(jnp.real(coeff_decay[:,Nx//2,Ny//2]))
    coeff_decay = coeff_decay.at[:,0,hfreqy:].set(jnp.conjugate(coeff_decay[:,0,1:Ny//2:-1]))
    coeff_decay = coeff_decay.at[:,Nx//2,hfreqy:].set(jnp.conjugate(coeff_decay[:,Nx//2,1:Ny//2:-1]))
    
    out = jnp.fft.irfft2(coeff_decay)
    out_GRF = jnp.zeros((data_num,Nx+1,Ny+1))
    out_GRF = out_GRF.at[:,:-1,:-1].set(out)
    out_GRF = out_GRF.at[:,-1,:-1].set(out[:,0,:])
    out_GRF = out_GRF.at[:,:-1,-1].set(out[:,:,0])
    out_GRF = out_GRF.at[:,-1,-1].set(out[:,0,0])
               
    return out_GRF

# RHS function object (reduced)
class fun_rhs_diffrax(eqx.Module):
    KX: jax.Array
    KY: jax.Array
    K2: jax.Array
    inv_K2: jax.Array
    nu: float
    f_hat: jax.Array
    de_alias: jax.Array

    # y == omega_curr_hat with half freqs for rfft2
    def __call__(self, t, y, args):
        # 1. Solve the Poisson equation (V-S) on the Fourier space. 
        psi_hat = self.inv_K2 * y
        
        # Recover partial derivatives on the physical space
        omega_x = jnp.fft.irfft2(1j*self.KX*y)
        omega_y = jnp.fft.irfft2(1j*self.KY*y)
        psi_x = jnp.fft.irfft2(1j*self.KX*psi_hat)
        psi_y = jnp.fft.irfft2(1j*self.KY*psi_hat)
        
        # 2. ODE in Fourier space
        lin_hat = -self.nu*self.K2*y + self.f_hat # linear term
        nonlin_hat = -jnp.fft.rfft2(omega_x*psi_y-omega_y*psi_x)*self.de_alias # nonlinear term, de-alised
        rhs_hat = lin_hat + nonlin_hat
        return rhs_hat
    
# @partial(jit, static_argnames=['args1','args2'])
# @jit
def solve_NS_step(omega_curr, args1, args2):
    timestamp, dt = args2
    terms = diffrax.ODETerm(fun_rhs_diffrax(*args1))
    omega_hat_curr = jnp.fft.rfft2(omega_curr)
    sol = diffrax.diffeqsolve(terms,diffrax.Tsit5(),t0=0,t1=timestamp,dt0=dt,y0=omega_hat_curr)
    return sol

def solve_NS_vorticity(omega_init,f,nu,timestamp=1,Nt=20):
    """
    Solve 2D incompressible N-S equation on the unit square [0,1]^2:
    (Vorticity-velocity)
    w_t = - u cdot grad_w + nu div(grad_w) + f,
    div u = 0, curl u = w,
    w(x,y,0) = w_0(x,y)
    with given external force f and periodic BC on the unit square.
    
    (Vorticity-Stream)
    w_t = - grad_perp_psi cdot grad_w + nu div(grad_w) + f
    -div(grad psi) = w, int psi = 0,
    w(x,y,0) = w_0(x,y)
    where grad_perp_psi cdot grad_w = omega_x psi_y - omega_y psi_x, curl(psi hat_z))=u.
    
    Solutions are generated by a pseudo-spectral scheme on the Fourier space.
    # Fourier space (Vorticity-Stream)
    # hat_w_t = -nu (kx^2+ky^2) hat_w - (hat_(w_x psi_y) - hat_(w_y psi_x)) + hat_f
    # hat_psi = hat_w / (kx^2+ky^2)
    # hat_w_t(K,0) = hat_w_0
    
    In: 
    - Init vorticity omega_init (Nx by Ny)
    - External force f (Nx by Ny)
    - nu (positive scalar)
    - timestamp (solution stored at each timestamps)
    - Nt (Number of timestamps)
    Out: 3D solution Omega (Nx by Ny by Nt) with Nt channel being solution at timestamps
    """
    
    # Create grid and set init condition
    Nx, Ny = jnp.shape(omega_init)[0]-1, jnp.shape(omega_init)[1]-1
    eps = 1e-12
    step_num = 1000
    dt = timestamp/step_num
    
    # Fourier wavenumbers
    pi = jnp.pi
    posnum_x = jnp.arange(0,Nx//2,1)
    negnum_x = jnp.arange(-Nx//2,0,1)
    posnum_y = jnp.arange(0,Ny//2,1)
    negnum_y = jnp.arange(-Ny//2,0,1)
    kx = 2*pi*jnp.concatenate((posnum_x, negnum_x))
    ky = 2*pi*jnp.concatenate((posnum_y, negnum_y))
    KX,KY = jnp.meshgrid(kx,ky,indexing='xy')
    K2 = KX**2 + KY**2
    inv_K2 = jnp.where(K2 > eps, K2**(-1), 0) # For the Poisson equation : hat_psi = hat_w / (kx^2+ky^2)
    
    # Orszag 2/3-Rule for de-aliasing
    de_alias = jnp.where(jnp.abs(KX) <= pi*Nx*2/3, 1, 0) * jnp.where(jnp.abs(KY) <= pi*Ny*2/3, 1, 0)
    
    # Fourier transform
    f_hat = jnp.fft.rfft2(f[:-1,:-1])
    
    # T=0:
    sol = jnp.zeros((Nx+1,Ny+1,Nt+1))
    sol = sol.at[:,:,0].set(omega_init)
    omega_curr = omega_init[:-1,:-1]
    args1 = (KX[:,:Ny//2+1], KY[:,:Ny//2+1], K2[:,:Ny//2+1], inv_K2[:,:Ny//2+1], nu, f_hat, de_alias[:,:Ny//2+1])
    args2 = (timestamp, dt)
    
    # Time update part (T->T+simestamp):
    for i in range(Nt):                
        sol_profile = solve_NS_step(omega_curr, args1, args2)
        next_hat = sol_profile.ys[-1]
    
        omega_next = jnp.fft.irfft2(next_hat) # next timestamp solution
        omega_curr = omega_next
        sol = sol.at[:-1,:-1,i+1].set(omega_curr)
        sol = sol.at[-1,:-1,i+1].set(omega_curr[0,:])
        sol = sol.at[:-1,-1,i+1].set(omega_curr[:,0])
        sol = sol.at[-1,-1,i+1].set(omega_curr[0,0])
    return sol

def main():
    # Directories and hyperparams
    data_dir = 'data/'
    data_name = 'NS_data_sample.mat'

    N_train, N_test = 1000, 100
    Nx, Ny, Nt = 128, 128, 20
    jx, jy = Nx//64, Ny//64
    timestamp = 1
    nu = 1e-3
    gamma, tau, sigma = 2.5, 7, 4
    xmin, xmax = 0, 1
    x = jnp.linspace(xmin, xmax, Nx+1)
    y = jnp.linspace(xmin, xmax, Ny+1)
    XX,YY = jnp.meshgrid(x,y,indexing='xy')
    f = 0.1 * (jnp.sin(2*jnp.pi*(XX+YY))+jnp.cos(2*jnp.pi*(XX+YY)))

    # train generation
    key = random.key(0)
    keys = random.split(key,N_train)
    input_train = GRF_2D_periodic(N_train, Nx, Ny, gamma, tau, sigma, key)
    output_train = jax.vmap(lambda omega: solve_NS_vorticity(omega,f,nu,timestamp,Nt))(input_train) # Faster but no progress bar, large memory overhead
       
    # for ind in tqdm(range(N_train)): # Slow but lower memory overhead and tqdm visible
    #     sol = solve_NS_vorticity(input_train[ind,:,:],f,nu,timestamp,Nt)
    #     output_train = output_train.at[ind,:,:,:].set(sol)

    # val generation
    key = random.key(113355)
    keys = random.split(key,N_test)
    input_val = GRF_2D_periodic(N_test, Nx, Ny, gamma, tau, sigma, key) 
    output_val = jax.vmap(lambda omega: solve_NS_vorticity(omega,f,nu,timestamp,Nt))(input_val)

    mdic = {"input_train": input_train[:,::jx,::jy], "output_train": output_train[:,::jx,::jy,:],
            "input_val": input_val[:,::jx,::jy], "output_val": output_val[:,::jx,::jy,:]}
    io.savemat(data_dir+data_name,mdic)
    
if __name__ == '__main__':    
    main()